### ISSUE TITLE
Resolutionable: decoding to incorrect value

### ISSUE THREAD

**Issue by rcw5** [FitnessKit/FitDataProtocol#11]
There's a minor bug in the [Resolutionable](https://github.com/FitnessKit/FitDataProtocol/blob/7df70f3ced6e0d292a02c2df40fd9b3349af9256/Sources/FitDataProtocol/Extensions/Resolutionable.swift#L75) code where encoding a value then decoding it doesn't result in the original value. This affects certain fields with an offset such as altitude/enhanced_altitude. Fields without offsets are unaffected.

This is because the offset is added last when encoding, but removed last when decoding.

e.g. current implementation:
```
original = 1000, scale = 5, offset = 500
encoded = (1000 * 5) + 500 = 5500
decoded = (5500 * (1/5)) - 500 = 600
```
If I opened my fit files in other tools I saw the incorrect decoded value which suggested it was a problem with the encoding of the data.

Looking at the FIT protocol it appears the encoding logic should add the offset first, then multiply by the scale factor. This will give the original value after decoding.

```
encoded = (1000 + 500) * 5 = 7500
decoded = (7500 * (1/5)) - 500 = 1000
```

**Comment by khoogheem** [comment]
Thanks for bringing this to my attention
 a 1.0.1 has been pushed out that fixes this issue.
