### ISSUE TITLE
Compilation Issue with Xcode 11.4 in FitDataProtocol

### ISSUE THREAD

**Issue by muzoman** [FitnessKit/FitDataProtocol#13]
Hi there,

Just updated to IOS 13.4 and Xcode 11.4 and rebuilt my App and had 49 of the same error message in the FitDataProtocol pod. Attached is example error:
![image](https://user-images.githubusercontent.com/320009/77537037-572d7200-6e95-11ea-9ee8-70f5c4a93d78.png)

**Comment by khoogheem** [comment]
hmm... I guess I didn't see that it was released...

there is a swift52 branch that should work for 11.4... 
I was waiting for a few more feedback before I merged it into master and updated Pods

**Comment by khoogheem** [comment]
sorry.. my mind was on bluetooth for some reason..

What version of the framework are you currently using...   looks like the 2.0.0??

**Comment by muzoman** [comment]
> sorry.. my mind was on bluetooth for some reason..
> 
> What version of the framework are you currently using... looks like the 2.0.0??

Yes 2.0.0

**Comment by muzoman** [comment]
I see a swift51 branch but no swift52?

**Comment by khoogheem** [comment]
> I see a swift51 branch but no swift52?

that was my mistake I was thinking about another project... It will take a few days, but I will have something for you here soon..  

sorry about the confusion

**Comment by muzoman** [comment]
> > I see a swift51 branch but no swift52?
> 
> that was my mistake I was thinking about another project... It will take a few days, but I will have something for you here soon..
> 
> sorry about the confusion

Ok, thanks Kevin.

**Comment by khoogheem** [comment]
@muzoman ok.. there is now a swift52 branch that you can check out... let me know.. and I will get it pushed to master if all looks good to you.

**Comment by muzoman** [comment]
Hi Kevin,
Looks good, thank you. Compilation errors are gone.

**Comment by khoogheem** [comment]
2.1.0 released
