### ISSUE TITLE
How to use? Any example projects?

### ISSUE THREAD

**Issue by mjunkmyjunk** [FitnessKit/FitDataProtocol#16]
thousand apologies for this daft question. But do not know how to begin to use this to encode files to FIT to be able to export it to Strava and the like. (I'm making my own bike app)

**Comment by khoogheem** [comment]
Let me know if the small example in the Readme is not enough... 
We try to be smart and provide Error messages if you are not using the correct FIT messages.. but some knowledge of FIT files is helpful to understand each of the Message Types

**Comment by mjunkmyjunk** [comment]
I just circled back to this (a few days ago) and thru some trial and error as well as some helpful code snippets from

https://github.com/FitnessKit/FitDataProtocol/issues/8#issuecomment-467544470

&

https://github.com/FitnessKit/FitDataProtocol/issues/12#issuecomment-546729298

I am able to do some rudimentary decoding (to get power / cad / hr / location) data.
I am also able to do some rudimentary encoding. But I do have issues in encoding ```leftRightBalance```

I'll open up a query and let this be closed
