### ISSUE TITLE
Calories

### ISSUE THREAD

**Issue by larcho** [FitnessKit/FitDataProtocol#2]
I'm currently working with a Zwift (Cycling app) .fit export file and I'm certain that it contains active calories data. But when I decode the file I get nil in the calories property in the RecordMessage type.

Maybe there is a global calories count somewhere but I'm not finding it. My file currently contains: FileIdMessage, DeviceInfoMessage, EventMessage, ActivityMessage and several RecordMessage.

By the way, I have 2 unknown message types. The Global Message IDs for the unknown types are 18 and 19. Where can I get a references for fit message types?

**Comment by larcho** [comment]
Found a reference for more Message Types. The data I'm looking for is in the Session and Lap message type. I'll implement those and try to push them here.

**Comment by khoogheem** [comment]
Hey Larcho -

I have those already in progress.. I should have something here by the weekend if that is good with you
