### ISSUE TITLE
how to encode some parameters which is not in convenience init

### ISSUE THREAD

**Issue by mjunkmyjunk** [FitnessKit/FitDataProtocol#20]
I am looking at ```leftRightBalance``` which is available and I am able to successfully decode this parameter in a ```fit``` file. 

However, when I try to encode this parameter(```leftRightBalance```), I can't seem to be able to call it. Looking at the ```RecordMessage.swift``` file, I noticed that the  number of parameters available in ```convenience init()``` is much much lesser than the one available in ```required init()```

Note: I am  actually not 100% certain how to encode the values but quite possibly just sending the Int value( %) of ```percentContribution``` and Marking ```right:true``` would work

I tried various google searches and StackOverflow searches but can't seem to locate instances where I can use a parameter which is not part of the ```convenience init()```. I _can_ however call the ```convenience init()```and omit certain parameters which the ```convenience init()``` will just mark it as ```nil```

Could you provide some guidance on this? Thanks.

<img width="1623" alt="Screenshot 2022-01-03 at 11 04 05 AM" src="https://user-images.githubusercontent.com/56195569/147897669-933e2f4d-25a9-4904-84d8-ec59ea2eb650.png">

I am able to omit certain parameters from the convenience init call. This is what I use to call the ```RecordMessage```

     let recordMessage = RecordMessage(
        timeStamp: FitTime(date: workoutStartDateTime.addingTimeInterval(Double(i))),
        position: myVlat.isEmpty ? nil : Position(latitude: Measurement(value: myVlat[i], unit: UnitAngle.degrees), longitude: Measurement(value: myVlon[i], unit: UnitAngle.degrees)),
        distance: dist.isEmpty ? nil : Measurement(value: Double(dist[i]), unit: UnitLength.meters),
        altitude: ergSlopeMode ? nil : Measurement(value: 10.0, unit: UnitLength.meters),
        power: power.isEmpty ? nil : Measurement(value: Double(power[i]), unit: UnitPower.watts),
        heartRate: hr.isEmpty ? nil : UInt8(hr[i]),
        cadence: cad.isEmpty ? nil : UInt8(cad[i])
      )

**Comment by mjunkmyjunk** [comment]
after many hours of SO and googling, I tried adding the ```leftRightBalance``` parameter into the directly into the pod's convenience init() like so at the very end of the ```convenience init``` method.

```
    public convenience init(timeStamp: FitTime? = nil,
                            position: Position? = nil,
                            distance: Measurement<UnitLength>? = nil,
                            timeFromCourse: Measurement<UnitDuration>? = nil,
                            cycles: UInt8? = nil,
                            totalCycles: UInt32? = nil,
                            accumulatedPower: Measurement<UnitPower>? = nil,
                            altitude: Measurement<UnitLength>? = nil,
                            speed: Measurement<UnitSpeed>? = nil,
                            power: Measurement<UnitPower>? = nil,
                            gpsAccuracy: Measurement<UnitLength>? = nil,
                            verticalSpeed: Measurement<UnitSpeed>? = nil,
                            calories: Measurement<UnitEnergy>? = nil,
                            verticalOscillation: Measurement<UnitLength>? = nil,
                            stanceTime: StanceTime? = nil,
                            heartRate: UInt8? = nil,
                            cadence: UInt8? = nil,
                            grade: Measurement<UnitPercent>? = nil,
                            resistance: UInt8? = nil,
                            cycleLength: Measurement<UnitLength>? = nil,
                            temperature: Measurement<UnitTemperature>? = nil,
                            activity: ActivityType? = nil,
                            torqueEffectiveness: TorqueEffectiveness? = nil,
                            pedalSmoothness: PedalSmoothness? = nil,
                            stroke: Stroke? = nil,
                            zone: UInt8? = nil,
                            ballSpeed: Measurement<UnitSpeed>? = nil,
                            deviceIndex: DeviceIndex? = nil,
                            leftRightBalance: LeftRightBalance? = nil) // Manually Added This in
                           {
        self.init()
        
        self.timeStamp = timeStamp
        self.position = position
        self.distance = distance
        self.timeFromCourse = timeFromCourse
        
        if let cycles = cycles {
            self.cycles = Measurement(value: Double(cycles), unit: self.$cycles.unitType)
        }
        if let totalCycles = totalCycles {
            self.totalCycles = Measurement(value: Double(totalCycles), unit: self.$totalCycles.unitType)
        }
        
        self.accumulatedPower = accumulatedPower
        self.altitude = altitude
        self.speed = speed
        self.power = power
        self.gpsAccuracy = gpsAccuracy
        self.verticalSpeed = verticalSpeed
        self.calories = calories
        self.verticalOscillation = verticalOscillation
        self.stanceTime = stanceTime
        
        if let hr = heartRate {
            self.heartRate = Measurement(value: Double(hr), unit: self.$heartRate.unitType)
        }
        
        if let cadence = cadence {
            self.cadence = Measurement(value: Double(cadence), unit: self.$cadence.unitType)
        }
        
        self.grade = grade
        self.resistance = resistance
        self.cycleLength = cycleLength
        self.temperature = temperature
        self.activity = activity
        self.torqueEffectiveness = torqueEffectiveness
        self.pedalSmoothness = pedalSmoothness
        self.stroke = stroke
        self.zone = zone
        self.ballSpeed = ballSpeed
        self.deviceIndex = deviceIndex
        self.leftRightBalance = leftRightBalance // Manually Added This In
```

and then I tried again to encode using this

```
      let recordMessage = RecordMessage(
        timeStamp: FitTime(date: workoutStartDateTime.addingTimeInterval(Double(i))),
        position: myVlat.isEmpty ? nil : Position(latitude: Measurement(value: myVlat[i], unit: UnitAngle.degrees), longitude: Measurement(value: myVlon[i], unit: UnitAngle.degrees)),
        distance: dist.isEmpty ? nil : Measurement(value: Double(dist[i]), unit: UnitLength.meters),
        altitude: ergSlopeMode ? nil : Measurement(value: 10.0, unit: UnitLength.meters),
        power: power.isEmpty ? nil : Measurement(value: Double(power[i]), unit: UnitPower.watts),
        heartRate: hr.isEmpty ? nil : UInt8(hr[i]),
        cadence: cad.isEmpty ? nil : UInt8(cad[I]),
        leftRightBalance: LeftRightBalance.init(percentContribution: 30, right: true)
      )
```

Result:
2022-01-03 14:47:42.0000  Power:73.0[70 - 30] LRBalance[ Cnt:1 Sum:100 Balance:[70% L / 30% R]

I'm fairly sure that this isn't the way to be doing this. Could you provide some guidance?

**Comment by khoogheem** [comment]
hmm..  I can't recall why they are not part of the init..
I need to go back and take a look why.. as a lot of those like grit and flow are pretty new values that were added to the protocol..

**Comment by mjunkmyjunk** [comment]
It would be greatly appreciated.  
Note that they are also not in the LapMessage.swift & SessionMessage.swift file convenience init (but they are in the init)

**Comment by khoogheem** [comment]
yah..I am pretty sure I was just looking to see if they got decoded (which is why they are in the init) and forgot about the encode ;)

**Comment by mjunkmyjunk** [comment]
The decode part works. I can parse a FIT file and it will spit out the L-R balance. 
Decode uses the ```required Init``` and Encode uses the ```convenience init()```? Is that how it works?

**Comment by khoogheem** [comment]
yep... the `init` setups the property wrappers to smarty decode the data.
and when encoding the vars are set via the convenience

**Comment by khoogheem** [comment]
there its a work in progress branch `leftRightBalance` which should have it and a few other fixes

**Comment by rbarthomeuf** [comment]
Hello,
To export FIT data to Strava, I need to send both Cadence and FractionalCadence.
If I only set cadence, Strava doubles the value (300 instead of 150).
What is the way to set fractional cadence ?
Thanks.

**Comment by khoogheem** [comment]
@rbarthomeuf that I just pushed up to master I will look at bumping tags here soon

**Comment by mjunkmyjunk** [comment]
@khoogheem Thanks for the new tag update. (tho I had to figure out how to actually use the specific tag)

Just putting it here in case it helps anyone
`  pod 'FitDataProtocol', :git => 'https://github.com/FitnessKit/FitDataProtocol.git', :tag => '2.1.2'`

I saw that one of the changes requested by @rbarthomeuf was for fractional cadence. @rbarthomeuf are you using this for cycling or running cadence? I am using it for cycling and sending the cadence data resulted in the correct data being displayed. 

```
 cadence: UInt8? = nil,
 fractionalCadence: Measurement<UnitCadence>?,
```

fractional cadence now also does not default to nil like cadence. Just checking if this is the intended behaviour?

**Comment by khoogheem** [comment]
it should be default to nil

**Comment by rbarthomeuf** [comment]
> @khoogheem Thanks for the new tag update. (tho I had to figure out how to actually use the specific tag)
> 
> Just putting it here in case it helps anyone ` pod 'FitDataProtocol', :git => 'https://github.com/FitnessKit/FitDataProtocol.git', :tag => '2.1.2'`
> 
> I saw that one of the changes requested by @rbarthomeuf was for fractional cadence. @rbarthomeuf are you using this for cycling or running cadence? I am using it for cycling and sending the cadence data resulted in the correct data being displayed. What are you using for fractional cadence? Values I've seen is either 0 or 0.5
> 
> and I found these links: [GoldenCheetah/GoldenCheetah#2060](https://github.com/GoldenCheetah/GoldenCheetah/issues/2060)
> 
> https://raw.githubusercontent.com/MaksVasilev/fit2gpx/44a0e45fbdc12839899d460825fc5866fba0229e/test/68MK1405.FIT.dump
> 
> ```
>  cadence: UInt8? = nil,
>  fractionalCadence: Measurement<UnitCadence>?,
> ```
> 
> fractional cadence now also does not default to nil like cadence. Just checking if this is the intended behaviour?

I use it for running.
For some reason, when exporting FIT to Strava, I have to use fractional cadence to have consistent data. If I don't use it, cadence is doubled in Strava

**Comment by mjunkmyjunk** [comment]
> I use it for running.
> For some reason, when exporting FIT to Strava, I have to use fractional cadence to have consistent data. If I don't use it, cadence is doubled in Strava

@rbarthomeuf please take a look at this answer from Garmin.

https://forums.garmin.com/developer/fit-sdk/f/discussion/288454/fractional-cadence-values

The function of the fractional Cadence is to get an Odd number instead of only always even number cadence.
