### ISSUE TITLE
Cannot find 'FITFileEncoder' in scope

### ISSUE THREAD

**Issue by breiko83** [FitnessKit/FitDataProtocol#25]
Hey - Installed FitDataProtocol via CocoaPod but I'm having troubles using the library for this error:
`Cannot find 'FITFileEncoder' in scope`

Here is my Pod file:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  pod 'Alamofire'
  pod 'FitDataProtocol', '~> 2.1'

  target 'MyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppUITests' do
    # Pods for testing
  end
end
```

And the class:
```
import Foundation
import FitDataProtocol

func generateFITFile() {
    let encoder = FITFileEncoder(dataValidityStrategy: .none) // build error here
}
```

I'm using Xcode 14.3 and installed via `pod install` - no errors or warnings were raised during installation.
I was also able to replicate the same error on a new project with no other frameworks installed.

Would you be able to help?

**Comment by khoogheem** [comment]
Looks like you have FIT in caps `FitFileEncoder(dataValidityStrategy`

**Comment by breiko83** [comment]
Oh dear. This is embarrassing. Thanks for your help.
