### ISSUE TITLE
Struggling to Encode FIT file - MessageIndex constructor marked as internal?

### ISSUE THREAD

**Issue by muzoman** [FitnessKit/FitDataProtocol#6]
Hi Kevin,

I'm trying to encode Workout and WorkoutStep Messages, but struggling - MessageIndex - No public constructor - how are you supposed to create one of these? The MessageIndex(value: value) func is marked as internal?

**Comment by khoogheem** [comment]
opps.. i will get a fix up for that

**Comment by khoogheem** [comment]
Just pushed up a new Build for SPM and CocoaPods 0.30.0
- Fixes the MessageIndex init
- Updates Encoding/Decoding methodology

Let me know if you run into any issues.
