### ISSUE TITLE
WorkoutStep Message incorrectly encoded?

### ISSUE THREAD

**Issue by muzoman** [FitnessKit/FitDataProtocol#7]
Hi Kevin,

I created a super simple test file to encode that included a single WorkoutStep message. I used your example code in the readme to do the encoding. The code executes without any errors but when I test its validity using the FIT SDK tool FITTestTool.jar it report that there's an error:

"Message index 32767 missing from workout_step messages."

I'm passing a MessageIndex created thus to the WorkoutStepMessage constructor:
MessageIndex(isSelected: true, value:UInt16(0))

I've attached the decoded CSV file that shows the data too

[testEncoding.csv.zip](https://github.com/FitnessKit/FitDataProtocol/files/2792121/testEncoding.csv.zip)

Any ideas?

**Comment by khoogheem** [comment]
make selected false.  So the odd thing is that the C lib looks like it brings in the MessageIndex with the Mask of 0x0FFF as 0x8000 is the selected bit.
So the encode looks correct.  But looks like maybe the C# and Java are not masking the numbers

I will make the default init set to false.

Also looks like WorkoutMesg doesn't need the message index and timestamp so I am going to remove those

**Comment by muzoman** [comment]
That's great, thank you Kevin. I must admit to being a little confused about what is meant by the "isSelected" flag.

**Comment by khoogheem** [comment]
Given there is SOOOOO much (yes that is sarcastic) documentation for the FIT files I am as well.  I think you are ok with keeping it not selected
