### ISSUE TITLE
Question if some mandatory attributes of record message could be made optional

### ISSUE THREAD

**Issue by mgmart** [FitnessKit/FitDataProtocol#8]
As one need special equipment to get the data for  ```stanceTime```, ```torqueEffectiveness```and ```pedalSmoothness```, I'm wondering if it could be possible to make them optional.

**Comment by mgmart** [comment]
Sorry, found the ```nilSelf```initialiser.

**Comment by khoogheem** [comment]
Good.. I should probably do a better job of showing that can be used.  
At the time I didn't like the look of an Optional Struct with Optional values inside, but it may be a better way to go in the long run

**Comment by mgmart** [comment]
Maybe it is of interest where your library is used:
https://github.com/WorkoutExporter/WorkoutExporter/pull/32

And, thank you very much. Without ```FitDataProtocol```we would not have fit file export within our app.
