### ISSUE TITLE
Over a Thousand Warnings in latest Xcode 10.2

### ISSUE THREAD

**Issue by muzoman** [FitnessKit/FitDataProtocol#9]
Hi there, 

Any plans to update the pod to Swift 5? I'm currently getting a lot of warnings like this:

 'public' modifier is redundant for instance method declared in a public extension

I've got the swift versions set to 4.2 at the moment, but the new Swift 5 compiler in Xcode 10.2 still spams me with these warnings.

**Comment by khoogheem** [comment]
Yep... That is correct ;)
I am in the process of updating all of the Items to Swift5, which will remove those warnings... Given there are some sharing of each of the Kits.. I need to try and release them all at once which is slowing me down a little.

**Comment by khoogheem** [comment]
So a couple things I am working on across the FitnesKit items.

- Get the Kits working with Accio (new way to use SPM for iOS projects)
- Branch all Kits into a last swift4 Branch
- Update all Kits into Swift5 with a new Major Number

**Comment by khoogheem** [comment]
@muzoman Just letting you know I am getting there in the Swift5 conversion.  I am in the process of also taking the time to clean things up.  Trimmed about 2k lines of redundant code already

**Comment by muzoman** [comment]
> @muzoman Just letting you know I am getting there in the Swift5 conversion. I am in the process of also taking the time to clean things up. Trimmed about 2k lines of redundant code already

That is a very satisfying thing to achieve, nice work Kevin!

**Comment by muzoman** [comment]
How's it going Kevin?

**Comment by khoogheem** [comment]
should be good to go now
